### ISSUE TITLE
Make the menu item collapsable with a button

### ISSUE THREAD

**Issue by udit-gulati** [kubiklabs/sharedsecurity-interface#2]

**Comment by udit-gulati** [comment]
Also, add the width changer for menu with drag and drop.

**Comment by DeepakS-Github** [comment]
Sir could you please clarify the meaning of drag and drop here.

**Comment by udit-gulati** [comment]
@DeepakS-Github It's similar to how you can inc/dec the width of filesystem explorer on the left in VSCode, the same you can do in Github when going through files in a repo.
